AZURE_OPENAI_API_KEY = ""
AZURE_OPENAI_API_TYPE = "azure"
AZURE_OPENAI_API_VERSION = "2022-12-01"
AZURE_OPENAI_API_BASE = "https://<your endpoint>.openai.azure.com"
OPENAI_OPENAI_API_KEY = ""
SERPAPI_API_KEY = ""
SERPER_API_KEY = ""